### ISSUE TITLE
This should be modified to use the `GetLatestBlockhash` method, as `GetRecentBlockhash` has been deprecated.

### ISSUE THREAD

**Issue by cocoyes** [ScribeSavant/raydium-swap-go#2]
https://github.com/ScribeSavant/raydium-swap-go/blob/a92944481e68d8e6cbf9ce97dca1bef84ff9bc50/raydium/liquidity/liquidity.go#L128

**Comment by ScribeSavant** [comment]
Done https://github.com/ScribeSavant/raydium-swap-go/commit/31b5f45728c308153725a34293ff83060abff1b4
